
services:
 main:
  build:
   context: .
   dockerfile: main.Dockerfile
  secrets:
    - source: env
      target: .env
 server:
  build:
   context: .
   dockerfile: server.Dockerfile
  ports:
   - "8000:8000"
  secrets:
    - source: env
      target: .env
secrets:
 env:
  file: ./.env