name: LinkedIn Posting

on:
  push:
    branch:
      - main

  schedule:
    - cron: "0 * * * *"

jobs:
  post_to_linkedin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository for python script
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependency
        run: pip install -r requirements.txt

      - name: Post to linkedIn
        env:
          RSS_FEED_URL: ${{ vars.RSS_FEED_URL }}
          REQUEST_URL: ${{ secrets.REQUEST_URL }}
          POSTING_CONTENT: ${{ vars.POSTING_CONTENT }}

        run: python main.py
